#!/usr/bin/env node

const fs = require("fs")
const marked = require("marked")
const prettier = require("prettier")

const html = marked(fs.readFileSync("./README.md").toString())

const content = `// This file was generated by ./scripts/generate-readme.js
import { h } from "hyperapp"

import { Link } from "../../../src"

export default function Readme() {
  return (
    <div class="content">
      ${html.replace("{", "&#123;").replace("}", "&#125;")}
    </div>
  )
}
`

fs.writeFileSync("./src/docs/pages/Home.js", prettier.format(content, { semi: false }))
